app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

ini_set('display_errors',true);

// Bridge between Myjob 2.0 and 1.0

Route::post('bridge', 'AdController@bridge');

// Important: real pages (i.e. no-redirect) should have the reverse bind in config/myjob.php

Route::get('disconnect', 'HomeController@disconnect');

Route::group(['middleware' => 'locales'], function () {

	Route::get('/', 'HomeController@index');

	Route::get('help', 'HelpController@index');
	Route::post('help', 'HelpController@send');

	Route::get('new-job', 'AdController@create');
	Route::post('new-job', 'AdController@store');

	Route::get('search', 'AdController@search');

	Route::get('forgotten-link', 'PublishersController@getForgottenLink');
	Route::post('forgotten-link', 'PublishersController@postForgottenLink');

	Route::get('{email}/{secret}', 'AdController@manage_ads_with_email');

	// require at least publisher access
	Route::group(['middleware' => 'publisher'], function () {

		Route::get('my-jobs', 'AdController@created');
		Route::get('job' . '/{ad}', 'AdController@show');
		Route::get('edit-job' . '/{ad}', 'AdController@edit');
		Route::put('edit-job' . '/{ad}', 'AdController@update');
		Route::get('delete-job' . '/{ad}', 'AdController@destroy');

		Route::get('enable-job' . '/{ad}', 'ModerationController@enable');
		Route::get('disable-job' . '/{ad}', 'ModerationController@disable');

	});

	// require at least tequila access
	Route::group(['middleware' => 'tequila'], function () {

		Route::get('jobs', 'AdController@index');

		Route::get('connect', 'HomeController@connect');

		Route::get('options', 'OptionsController@index');
		Route::put('options', 'OptionsController@update');

	});

	// require at least admin access
	Route::group(['middleware' => ['tequila', 'admin']], function () {

		Route::get('moderation', 'ModerationController@adsToModerate');
		Route::get('accept-job/{ad}', 'ModerationController@accept');
		Route::get('refuse-job/{ad}', 'ModerationController@refuse');

	});

});

app/Models/Ad.php
<?php

namespace Myjob\Models;

use Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Log;
use Session;

class Ad extends Model {

	use SoftDeletes;

	protected $primaryKey = 'url';
	protected $fillable = [
		'title', 'category_id', 'place', 'description',
		'starts_at', 'ends_at', 'duration', 'salary', 'skills', 'languages',
		'contact_first_name', 'contact_last_name', 'contact_email', 'contact_phone',
	];

	const WEEK = 7 * 24 * 3600;


	public static function withCategories() {
		return self::join('categories', 'ads.category_id', '=', 'categories.category_id');
	}

	public static function withVisitors() {
		return Auth::guest() ? self::where('contact_email', '=', Session::get('connected_visitor')): new static;
	}

	public static function withCategoriesVisitors() {
		return Auth::guest() ? self::withCategories()->where('contact_email', '=', Session::get('connected_visitor')): self::withCategories();
	}

	// Overrides create function
	public static function create(array $data = []) {

		foreach (config('data.ad') as $field => $filters) {
			if (!isset($filters['required']) && isset($data[$field]))
				$data[$field] = self::nullable($data[$field]);
		}

		if (isset($data['starts_at'], $data['ends_at']) && $data['starts_at'] == $data['ends_at'])
			$data['ends_at'] = null;

		$ad = new Ad($data); // mass-alignement allowed on fillable
		assert(isset($ad->title), "Create without all datas.");
		$url = self::generate_url($ad->title);

		$ad->url = $url;
		$ad->random_secret = str_random(32);
		$ad->expires_at = formatDate(time() + config('myjob.ads.validityWeeks') * self::WEEK);

		$ad->save();
		$ad->url = $url; // reset $ad->url as it is only the primary key in Laravel and was altered by save
		Log::info('Ad ' . e($ad->title) . ' created.');
		return $ad;
	}

	public function fill(array $data) {

		foreach (config('data.ad') as $field => $filters) {
			if (!isset($filters['required']) && isset($data[$field]))
				$data[$field] = self::nullable($data[$field]);
		}

		if (isset($data['starts_at'], $data['ends_at']) && $data['starts_at'] == $data['ends_at'])
			$data['ends_at'] = null;

		if (isset($data['description']))
			$data['description'] = self::prettyText($data['description']);

		if (isset($data['contact_phone']))
			$data['contact_phone'] = self::prettyPhone($data['contact_phone']);

		return parent::fill($data);
	}

	public static function acceptedAd($fields) {
		return Ad::withCategoriesVisitors()->select($fields)
			->whereNotNull('validated_at')
			->where('expires_at', '>', date('Y-m-d H:i:s'))
			->where('validated', '=', true);
	}

	public function getDates() {
		return array_merge(parent::getDates(), ['starts_at', 'ends_at', 'validated_at']);
	}

	// Return TRUE if visitor has rights to see the ad
	public function canBeSeen() {
		return Auth::check() || (Session::has('connected_visitor') && Session::get('connected_visitor') == $this->contact_email);
	}

	/** Generates a new unique and readable url **/
	private static function generate_url($ad_name) {
		$new_url = Str::slug($ad_name, "-");

		if (self::url_is_unique($new_url))
			return $new_url;

		$i = 0;
		do {
			$new_url_num = $new_url . '-' . $i;
			$i++;
		} while (!self::url_is_unique($new_url_num));

		return $new_url_num;
	}

	private static function url_is_unique($url) {
		return self::where('url', '=', $url)->count() == 0;
	}

	private static function nullable($field) {
		return isset($field) && !empty($field) ? $field: null;
	}

	private static function prettyText($text) {
		if (substr($text, -1) != '.') $text .= '.';
		return ucfirst($text);
	}

	private static function prettyPhone($phone) {

		$phone = str_replace(' ', '', $phone);
		$formated = '';
		$length = strlen($phone);
		$index = 0;

		if (substr($phone, 0, 1) == '+') { // +4121.. -> +41 22 ..
			$formated .= '+' . substr($phone, 1, 2) . ' ' . substr($phone, 3, 2) . ' ';
			$index = 5;
		} else if (substr($phone, 0, 2) == '00') { // 004121.. -> +41 22 ..
			$formated .= '+' . substr($phone, 2, 2) . ' ' . substr($phone, 4, 2) . ' ';
			$index = 4;
		} else { // 021.. -> 021 ..
			$formated .= substr($phone, 0, 3) . ' ';
			$index = 3;
		}

		// 3-chunk
		$formated .= substr($phone, $index, 3) . ' ';
		$index += 3;

		// chunk by 2
		while ($length >= $index) {
			$formated .= substr($phone, $index, 2) . ' ';
			$index += 2;
		}

		assert(strlen($phone) == strlen(str_replace(' ', '', $formated)));
		return trim($formated);
	}
}

app/Http/Controllers/AdController.php
<?php

namespace Myjob\Http\Controllers;

use App;
use Auth;
use Input;
use Myjob\Models\Ad;
use Myjob\Models\Category;
use Myjob\Models\Publisher;
use Redirect;
use Session;
use Validator;
use Request;
use Mail;
use Log;

class AdController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index() {
		$fields = ['url',
			'title', 'name_' . App::getLocale() . ' AS category',
			'description',
			'place',
			'ads.updated_at'];

		$ads = Ad::acceptedAd($fields)->simplePaginate(config('myjob.ads.numberDisplay'));
		return view('ads.index', ['ads' => $ads]);
	}

	/**
	 * Show ads created by connected publisher
	 */
	public function created() {
		$fields = ['url',
			'title', 'name_' . App::getLocale() . ' AS category',
			'description',
			'place',
			'ads.updated_at'];

		$publisher = Auth::check() ? Auth::user()->email: Session::get('connected_visitor');
		$ads = Ad::withCategories()->where('contact_email', '=', $publisher)->select($fields)->simplePaginate(config('myjob.ads.numberDisplay'));
		return view('ads.index', ['ads' => $ads]);
	}

	/** Each Myjob 1.0 job creation request redirects its data here. */
	public function bridge() {
		$data = array_map(function($e) { return trim($e); }, Input::all());
		$getOrElse = function($e) use (&$data) { return array_key_exists($e, $data) ? $data[$e] : 'N/A'; };

		$email = $getOrElse('email');
		$bridgedAd = [
			'title' => ucfirst(strtolower($getOrElse('titre'))),
			'category_id' => 9,
			'place' => 'N/A',
			'description' => '[IMPORTED] ' . $getOrElse('description'),
			'starts_at' => date('Y-m-d H:i:s'),
			'ends_at' => null,
			'duration' => $getOrElse('duree') . ' jours',
			'salary' => $getOrElse('renumeration'),
			'skills' => $getOrElse('competence'),
			'languages' => $getOrElse('langues') == '2' ? 'français' : $getOrElse('langues') == '18' ? 'allemand' : 'anglais',
			'contact_first_name' => $getOrElse('contact'),
			'contact_last_name' => '',
			'contact_email' => $email,
			'contact_phone' => null
		];

		Log::debug(print_r($data, true) . print_r($bridgedAd, true));

		if (!Publisher::exists($email)) {
			Publisher::new_publisher($email);
		}

		$ad = Ad::create($bridgedAd);
		Log::info('Bridged ' . e($ad->title) . ' ad.');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create() {
		$categories = Category::get_id_name_mapping();
		return view('ads.new', ['categories' => $categories, 'ad' => null]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store() {
		$categories = Category::get_id_name_mapping();
		$validator = Validator::make(Input::all(), $this->adValidation());
		$validator->setAttributeNames(array_map('strtolower', trans('ads.labels')));

		if ($validator->fails()) {
            return back()->withInput()->withErrors($validator);
        }

		/* If this is the first ad with that email,
		create new publisher */

		$email = Input::get('contact_email');
		if (!Publisher::exists($email)) {
			$publisher = Publisher::new_publisher($email);

			Mail::send('emails.publishers', ['email' => $email, 'secret' => $publisher->random_secret], function ($m) use (&$email) {
					$m->to($email)->subject(trans('mails.publishers.link'));
			});

			Log::info("New user ". $email . ", mail sent with admin link");
		}

		$ad = Ad::create(Input::all());

		// Success message
		Session::flash('success', trans('general.successes.adcreated'));

		// Redirection to ad if allowed
		if ($ad->canBeSeen()) {
			return redirect()->action('AdController@show', $ad->url);
		} else {
			return redirect()->action('HomeController@index');
		}


	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function show($url) {

		$fields = ['url',
			'title', 'name_' . App::getLocale() . ' AS category', 'place', 'description',
			'starts_at', 'ends_at', 'duration', 'salary', 'skills', 'languages',
			'contact_first_name', 'contact_last_name', 'contact_email', 'contact_phone',
			'validated', 'expires_at', 'ads.updated_at'];

		$ad = Ad::withCategoriesVisitors()->select($fields)->findOrFail($url);

		return view('ads.show', ['ad' => $ad]);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function edit($url) {
		$ad = Ad::withVisitors()->findOrFail($url);
		$categories = Category::get_id_name_mapping();
		$now = formatDate();

		if ($ad->starts_at < $now) $ad->starts_at = $now;
		if ($ad->ends_at < $now) $ad->ends_at = null;

		return view('ads.edit', ['categories' => $categories, 'ad' => $ad]);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function update($url) {
		$ad = Ad::withVisitors()->findOrFail($url);
		$validator = Validator::make(Input::all(), $this->adValidation());
		$validator->setAttributeNames(array_map('strtolower', trans('ads.labels')));

		if ($validator->fails())
			return back()->withInput()->withErrors($validator);

		if (Input::has('contact_email')) {
			$newContactEmail = Input::get('contact_email');

			if ($newContactEmail != $ad->contact_email && !Publisher::exists($email)) {
				Publisher::new_publisher($email);
			}
		}

		$ad->fill(Input::all());
		$ad->save();

        Log::info('update ad: ' . $ad->url);

        return redirect()->action('AdController@show', $url);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function destroy($url) {
		$ad = Ad::withVisitors()->findOrFail($url);
		$ad->delete();

        Log::info('delete ad: ' . $ad->url);

        return redirect()->action('AdController@index');
	}

	/**
	 * Displays the ads created by the person with
	 * the @param $email email
	 */
	public function manage_ads_with_email($email, $secret) {
		if (Publisher::is_valid($secret, $email)) {
			/* Disconnect previous sessions */
			Controller::disconnect();

			/* Temporarily allow current visitor to edit all ads with email $email. */
			Session::put('connected_visitor', $email);
			return redirect()->action('AdController@created');
		} else {
			App::abort(404);
		}
	}

	public function search() {

		if (Auth::guest())
			return redirect()->action('HelpController@index');

		$raw = trim(Input::get('q'));
		if (empty($raw))
			return redirect()->action('AdController@index');

		$terms = explode(' ', $raw);

		$fields = ['url',
			'title', 'name_' . App::getLocale() . ' AS category',
			'description',
			'place',
			'ads.updated_at'];

		$query = Auth::user()->admin ? Ad::withCategories()->select($fields): Ad::acceptedAd()->select($fields);
		$searchFields = ['title', 'description', 'place', 'skills', 'languages', 'name_' . App::getLocale(), 'contact_email'];

		foreach ($terms as $t) {
			$query->where(function ($query) use (&$t, &$searchFields) {
				foreach ($searchFields as $f) {
					$query->Orwhere($f, 'LIKE', '%' . $t . '%');
				}
			});
		}
		$ads = $query->simplePaginate(config('myjob.ads.numberDisplaySearch'));

        Log::debug('search for ' . e($raw));

		return view('ads.search', ['ads' => $ads, 'search' => $raw]);
	}

	protected function adValidation() {

		$filters = parent::validation('ad');

		$filters['contact_email'][] = 'email';
		$filters['category_id'][] = 'in:' . implode(',', Category::get_id_name_mapping()->keys()->all());
		$filters['starts_at'][] = 'after: -1 day';
		$filters['ends_at'][] = 'after:' . Input::get('starts_at') . ' -1 day';

		$filters = array_map(function ($f) {
			return implode('|', $f);
		}, $filters);

		return $filters;
	}

}

resources/views/ads/elements/advices.blade.php
<h3 class="ui header">{{ trans('general.titles.apply') }}</h3>
<p>{{ trans('general.texts.apply') }}</p>

resources/views/ads/elements/display.blade.php
<div class="ui internally celled stackable grid segment">
    <div class="row">
        <div class="ten wide column">
            <p>{{ $ad->description }}</p>
        </div>
        <div class="six wide column">
            <div class="ui list">
                <div class="item">
                    <i class="tag icon"></i>

                    <div class="content">
                        {{ $ad->category }}
                    </div>
                </div>
                <div class="item">
                    <i class="wait icon"></i>

                    <div class="content">
                        <span class="calendar">{{ $ad->updated_at }}</span>
                    </div>
                </div>
                <div class="item">
                    <i class="pin icon"></i>

                    <div class="content">
                        {{ $ad->place }}
                    </div>
                </div>
                <div class="item">
                    <i class="user icon"></i>

                    <div class="content">
                        {{ $ad->contact_first_name }} {{ $ad->contact_last_name }}
                    </div>
                </div>
                <div class="item">
                    <i class="mail icon"></i>

                    <div class="content">
                        <a href="mailto:{{ $ad->contact_email }}?subject={{ $ad->title }}">{{ $ad->contact_email }}</a>
                    </div>
                </div>
                @if (isset($ad->contact_phone))
                    <div class="item">
                        <i class="phone icon"></i>

                        <div class="content">
                            {{ $ad->contact_phone }}
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
    <div class="row">
        <div class="eight wide column">
            <div class="ui list">
                <div class="item">
                    <div class="header">{{ label('skills') }}</div>
                    <p>{{ $ad->skills or trans('general.undefined') }}</p>
                </div>
                <div class="item">
                    <div class="header">{{ label('languages') }}</div>
                    <p>{{ $ad->languages or trans('general.undefined') }}</p>
                </div>
            </div>
        </div>
        <div class="eight wide column">
            <div class="ui list">
                <div class="item">
                    <div class="header">{{ trans('general.dates') }}</div>
                    <p>
                        <span class="date">{{ $ad->starts_at }}</span>
                        @if (isset($ad->ends_at))
                            {{ trans('general.todate') }} <span class="date">{{ $ad->ends_at }}</span>
                        @endif
                    </p>
                </div>
                <div class="item">
                    <div class="header">{{ label('duration') }}</div>
                    <p>{{ $ad->duration }}</p>
                </div>
                <div class="item">
                    <div class="header">{{ label('salary') }}</div>
                    <p>{{ $ad->salary }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/ads/elements/form.blade.php
@if ($errors->any())
    <div class="ui error visible message">
        <ul class="list">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="ui segment">
    <div class="ui top attached label caps">{{ trans('ads.sections.general') }}</div>
    <div class="field">
        <label>{{ label('title') }}</label>
        {!! Form::text('title', null, adform('title')) !!}
    </div>
    <div class="two fields">
        <div class="field">
            <label>{{ label('category_id') }}</label>
            {!! Form::select('category_id', $categories, null, adform('category_id')) !!}
        </div>
        <div class="field">
            <label>{{ label('place') }}</label>
            {!! Form::text('place', null, adform('place')) !!}
        </div>
    </div>
</div>

<div class="ui segment">
    <div class="ui top attached label caps">{{ trans('ads.sections.details') }}</div>
    <div class="two fields">
        <div class="field">
            <label>{{ label('starts_at') }}
                <small>({{ trans('general.startingtoday') }})</small>
            </label>
            {!! Form::text('starts_at', prefill($ad, date('c')), adform('starts_at')) !!}
        </div>
        <div class="field">
            <label>{{ label('ends_at') }}
                <small>({{ trans('general.optional') }})</small>
            </label>
            {!! Form::text('ends_at', null, adform('ends_at')) !!}
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label>{{ label('duration') }}</label>
            {!! Form::text('duration', null, adform('duration')) !!}
        </div>
        <div class="field">
            <label>{{ label('salary') }}</label>
            {!! Form::text('salary', null, adform('salary')) !!}
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label>{{ label('skills') }}
                <small>({{ trans('general.optional') }})</small>
            </label>
            {!! Form::text('skills', null, adform('skills')) !!}
        </div>
        <div class="field">
            <label>{{ label('languages') }}
                <small>({{ trans('general.optional') }})</small>
            </label>
            {!! Form::text('languages', null, adform('languages')) !!}
        </div>
    </div>
</div>

<div class="ui segment">
    <div class="ui top attached label caps">{{ trans('ads.sections.main') }}</div>
    <div class="field">
        <label>{{ label('description') }}</label>
        {!! Form::textarea('description', null, adform('description')) !!}
    </div>
</div>

<div class="ui segment">
    <div class="ui top attached label caps">{{ trans('ads.sections.publisher') }}</div>
    <div class="two fields">
        <div class="field">
            <label>{{ label('contact_first_name') }}</label>
            {!! Form::text('contact_first_name', isset($user) ? prefill($ad, $user): null, adform('contact_first_name')) !!}
        </div>
        <div class="field">
            <label>{{ label('contact_last_name') }}</label>
            {!! Form::text('contact_last_name', isset($user_last) ? prefill($ad, $user_last): null, adform('contact_last_name')) !!}
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label>{{ label('contact_email') }}</label>
            {!! Form::email('contact_email', isset($user_email) ? prefill($ad, $user_email): null, adform('contact_email')) !!}
        </div>
        <div class="field">
            <label>{{ label('contact_phone') }}
                <small>({{ trans('general.optional') }})</small>
            </label>
            {!! Form::text('contact_phone', null, adform('contact_phone')) !!}
        </div>
    </div>
</div>

resources/views/ads/elements/list.blade.php
@forelse ($ads as $ad)
    <div class="column">
        <a class="ui fluid card" href="{{ action('AdController@show', $ad->url) }}">
            <div class="content">
                <div class="right floated">{{ $ad->category }}</div>
                <div class="header">{{ $ad->title }}</div>
                <div class="meta">
                    <span class="right floated moment">{{ $ad->updated_at }}</span>
                    {{ $ad->place }}
                </div>
                <div class="description">
                    <p>{{ $ad->description }}</p>
                </div>
            </div>
        </a>
    </div>
@empty
    <p>{{ trans('general.nothingleft') }}</p>
@endforelse

resources/views/ads/elements/news.blade.php
<h3 class="ui header">{{ trans('general.titles.news') }}</h3>
<p>{{ trans('general.texts.news') }}</p>
<a class="ui small red icon button mt" href="{{ action('HelpController@index') }}">
    <i class="write icon"></i>
    {{ trans('general.buttons.feedback') }}
</a>

resources/views/ads/elements/paginate.blade.php
@if ($ads->hasMorePages() || $ads->currentPage() > 1)
    <div class="align-center">
        @if ($ads->currentPage() > 1)
            <a href="{{ $ads->url($ads->currentPage() - 1) }}{{ isset($search) ? '&q=' . e($search): '' }}"
               class="ui red icon button">
                <i class="arrow circle left icon"></i>
                Page précédente
            </a>
        @endif
        @if ($ads->hasMorePages())
            <a href="{{ $ads->nextPageUrl() }}{{ isset($search) ? '&q=' . e($search): '' }}" class="ui red icon button">
                Page suivante
                <i class="arrow circle right icon"></i>
            </a>
        @endif
    </div>
@endif

resources/views/ads/elements/rules.blade.php
<h3 class="ui header">{{ trans('general.titles.managing') }}</h3>
<p>{!! trans('general.texts.rules.visibility') !!}</p>
<a class="ui small red icon button mt" href="{{ url('forgotten-link') }}">
    <i class="repeat icon"></i>
    {{ trans('general.buttons.recover') }}
</a>
<h3 class="ui header">{{ trans('general.titles.conditions') }}</h3>
<p>{{ trans('general.texts.rules.respect') }}</p>
<ol class="ui list">
    <li>{!! trans('general.texts.rules.rule1') !!}</li>
    <li>{!! trans('general.texts.rules.rule2') !!}</li>
    <li>{!! trans('general.texts.rules.rule3') !!}</li>
    <li>{!! trans('general.texts.rules.rule4') !!}</li>
</ol>
<a class="ui small red button mt" href="{{ action('HelpController@index') }}">
    <i class="help icon"></i>
    {{ trans('general.buttons.ask') }}
</a>